spring:
    datasource:
        url: jdbc:mysql://localhost:3306/mybatis_flex?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
server:
    port: 10004
eureka:
    client:
        service-url:
            defaultZone: http://localhost:10000/eureka