spring:
    application:
        name: mybatis-flex
    profiles:
        active: sqlserver
server:
    port: 10004
    servlet:
        context-path: /flex
eureka:
    client:
        service-url:
            defaultZone: http://localhost:10000/eureka