spring:
    datasource:
        url: jdbc:postgresql://localhost:15433/postgres?reWriteBatchedInserts=true&useServerPrepStmts=true
        username: postgres
        password: password
mybatis-plus:
    configuration:
        cache-enabled: true
        use-generated-keys: true
        default-executor-type: REUSE
        use-actual-param-name: true
    global-config:
        db-config:
            db-type: postgresql