spring:
    application:
        name: mybatis-flex
    profiles:
        active: pg
#        active: sqlserver
server:
    port: 10004
    servlet:
        context-path: /flex
eureka:
    instance:
        hostname: localhost
    client:
        service-url:
              defaultZone: http://192.168.210.111:10000/eureka/