server:
  port: 10000
eureka:
  client:
    register-with-eureka: false  #false:不作为一个客户端注册到注册中心
    fetch-registry: false      #为true时，可以启动，但报异常：Cannot execute request on any known server
    instance-info-replication-interval-seconds: 10
    service-url:
      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost